-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 20:25:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `ID_curso` INT NULL,
  `numero_da_turma` INT NULL,
  `nome_do_curso` VARCHAR(45) NULL,
  `ID_turma` INT NULL,
  `ID_turma` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`turma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `ID_turma` INT NULL,
  `quantidade_alunos` INT NULL,
  `nome_aluno` VARCHAR(25) NULL,
  `sobre_nome_aluno` VARCHAR(35) NULL,
  `nome_do_curso` VARCHAR(20) NULL,
  `ID_curso` INT NULL,
  PRIMARY KEY (`ID_turma`),
  INDEX `fk_turma_cursos1_idx` (`ID_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turma_cursos1`
    FOREIGN KEY (`ID_curso`)
    REFERENCES `mydb`.`cursos` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `ID_aluno` INT NULL,
  `nome` VARCHAR(100) NULL,
  `sobre_nome` VARCHAR(100) NULL,
  `cpf` CHAR(11) NULL DEFAULT '',
  `sexo` VARCHAR(45) NULL,
  `cursos_ID_curso` INT NOT NULL,
  `turma_ID_turma` INT NOT NULL,
  PRIMARY KEY (`ID_aluno`),
  INDEX `fk_aluno_cursos1_idx` (`cursos_ID_curso` ASC) VISIBLE,
  INDEX `fk_aluno_turma1_idx` (`turma_ID_turma` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_cursos1`
    FOREIGN KEY (`cursos_ID_curso`)
    REFERENCES `mydb`.`cursos` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_ID_turma`)
    REFERENCES `mydb`.`turma` (`ID_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
